# pgp:'A2B73FB4DA0891B38EECD35B47991CD146C9C4BC' # https://keybase.io/trungdlpwolffun

# age: age1hcthyar6ujws8nmycmvh46f4luptqdxgf90z2a3ducedwmfvzedq7veutp # ci-runner

creation_rules:
  - pgp: >-
      A2B73FB4DA0891B38EECD35B47991CD146C9C4BC
    age: >-
      age1hcthyar6ujws8nmycmvh46f4luptqdxgf90z2a3ducedwmfvzedq7veutp
