default_ethereum_client_images:

  prysm: gcr.io/prysmaticlabs/prysm/beacon-chain:v4.2.1-rc.1
  prysm_validator: gcr.io/prysmaticlabs/prysm/validator:v4.2.1-rc.1
  nethermind: nethermindeth/nethermind:ca24d87
nethermind_container_command_extra_args:
  - --Init.ChainSpecPath=/network-config/chainspec.json
  - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
  - --Discovery.Bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --Init.IsMining=false
  - --Pruning.Mode=None
  - --config=none.cfg
  - --EthStats.Enabled=true
  - --EthStats.Name={{ inventory_hostname }}
  - --EthStats.Secret={{ ethstats_secret }}
  - --EthStats.Server=wss://{{ ethstats_url }}/api/
  - --log=DEBUG
  - --TxPool.BlobsSupport=StorageWithReorgs
  - --TxPool.ReportMinutes=5
