geth_container_command_extra_args:
  - --http.api=eth,net,web3,debug,admin,txpool
  - --http.vhosts=*
  - --networkid={{ ethereum_network_id }}
  - --syncmode=full
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --ethstats={{ inventory_hostname }}:{{ ethstats_secret }}@{{ ethstats_url }}
  - --metrics.expensive
  - --pprof
  - --pprof.addr=0.0.0.0

geth_container_command:
  - --datadir=/data
  - --port={{ geth_ports_p2p }}
  - --http
  - --http.addr=0.0.0.0
  - --http.port={{ geth_ports_http_rpc }}
  - --authrpc.addr=0.0.0.0
  - --authrpc.port={{ geth_ports_engine }}
  - --authrpc.vhosts=*
  - --authrpc.jwtsecret=/execution-auth.jwt
  - --nat=extip:{{ geth_announced_ip }}
  - --metrics
  - --metrics.port={{ geth_ports_metrics }}

teku_container_command_extra_args:
  - --network=/network-config/config.yaml
  - --genesis-state=/network-config/genesis.ssz
  - --p2p-discovery-bootnodes={{ ethereum_cl_bootnodes | join(',') }}
  - --p2p-peer-upper-bound=100
  - --data-storage-non-canonical-blocks-enabled=true
  - --data-storage-mode=PRUNE
  - --validators-graffiti={{ ansible_hostname }}🐼
  - --logging={{ log_level | default('debug') }}
  - --Xlog-include-p2p-warnings-enabled
  - --metrics-block-timing-tracking-enabled
  - --Xpeer-rate-limit=100000
  - --Xpeer-request-limit=1000
  - --ignore-weak-subjectivity-period-enabled
  - --checkpoint-sync-url={{ checkpoint_sync_url }}
default_ethereum_client_images:
  teku: consensys/teku:24.1.1
  geth: ethpandaops/geth:master-47d76c5
geth_container_ports:
  - "127.0.0.1:{{ geth_ports_http_rpc }}:{{ geth_ports_http_rpc }}"
  - "127.0.0.1:{{ geth_ports_engine }}:{{ geth_ports_engine }}"
  - "{{ geth_ports_p2p }}:{{ geth_ports_p2p }}"
  - "{{ geth_ports_p2p }}:{{ geth_ports_p2p }}/udp"
  - "127.0.0.1:{{ geth_ports_metrics }}:{{ geth_ports_metrics }}"
