geth_container_command_extra_args:
  - --http.api=eth,net,web3,debug,admin,txpool
  - --http.vhosts=*
  - --networkid={{ ethereum_network_id }}
  - --syncmode=full
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --ethstats={{ inventory_hostname }}:{{ ethstats_secret }}@{{ ethstats_url }}
  - --metrics.expensive

teku_container_command_extra_args:
  - --network=/network-config/config.yaml
  - --genesis-state=/network-config/genesis.ssz
  - --p2p-discovery-bootnodes={{ ethereum_cl_bootnodes | join(',') }}
  - --p2p-peer-upper-bound=100
  - --data-storage-non-canonical-blocks-enabled=true
  - --data-storage-mode=PRUNE
  - --validators-graffiti={{ ansible_hostname }}🐼
  - --logging={{ log_level | default('debug') }}
  - --Xlog-include-p2p-warnings-enabled
  - --metrics-block-timing-tracking-enabled
  - --Xpeer-rate-limit=100000
  - --Xpeer-request-limit=1000
  - --ignore-weak-subjectivity-period-enabled
  - --checkpoint-sync-url={{ checkpoint_sync_url }}
default_ethereum_client_images:
  teku: consensys/teku:24.1.1
  geth: ethpandaops/geth:karalabe-blobpool-crash-cleanup-ca5228c
