# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: dencun-devnet-12
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: true
      addresses:
        dencun-devnet-12: https://checkpoint-sync.dencun-devnet-12.ethpandaops.io
    clientArgs:
      networks:
        dencun-devnet-12:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://59744008cb2de257daf3bdaa4fa34428c447e82705893be42a7407f20a84e45231b942c56e6bd771cbfb79c13b08eb85a002fe78cfd0c19b8634505aabed01db@64.226.104.183:30303?discport=30303,enode://ba216cbfc0fdc8718fe57abc1bf91bc98b584ad441b4f19b0c68ed5349c65d8cfe0e0a017df209452723d3bcd1949fe14cbde5cd5e2088d6bedd4af3a6739ece@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>@ethstats.dencun-devnet-12.ethpandaops.io:443
              - --Xfilter-on-enr-fork-id=true
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://59744008cb2de257daf3bdaa4fa34428c447e82705893be42a7407f20a84e45231b942c56e6bd771cbfb79c13b08eb85a002fe78cfd0c19b8634505aabed01db@64.226.104.183:30303?discport=30303,enode://ba216cbfc0fdc8718fe57abc1bf91bc98b584ad441b4f19b0c68ed5349c65d8cfe0e0a017df209452723d3bcd1949fe14cbde5cd5e2088d6bedd4af3a6739ece@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none.cfg
              - --EthStats.Enabled=true
              - --EthStats.Name=k8s-teku-geth-001
              - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>
              - --EthStats.Server=wss://ethstats.dencun-devnet-12.ethpandaops.io/api/
              - --log=INFO
              - --TxPool.BlobsSupport=StorageWithReorgs
              - --TxPool.ReportMinutes=5
            geth:
              - --http.api=eth,net,web3,debug,admin,txpool
              - --http.vhosts=*
              - --state.scheme=path
              - --networkid=7011893062
              - --syncmode=full
              - --bootnodes=enode://59744008cb2de257daf3bdaa4fa34428c447e82705893be42a7407f20a84e45231b942c56e6bd771cbfb79c13b08eb85a002fe78cfd0c19b8634505aabed01db@64.226.104.183:30303?discport=30303,enode://ba216cbfc0fdc8718fe57abc1bf91bc98b584ad441b4f19b0c68ed5349c65d8cfe0e0a017df209452723d3bcd1949fe14cbde5cd5e2088d6bedd4af3a6739ece@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>@ethstats.dencun-devnet-12.ethpandaops.io
              - --rpc.allow-unprotected-txs
              - --verbosity=4
              - --snapshot=false
            erigon:
              - --chain=dev
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --prune=htc
              - --networkid=7011893062
              - --db.size.limit=100GB
              - --bootnodes=enode://59744008cb2de257daf3bdaa4fa34428c447e82705893be42a7407f20a84e45231b942c56e6bd771cbfb79c13b08eb85a002fe78cfd0c19b8634505aabed01db@64.226.104.183:30303?discport=30303,enode://ba216cbfc0fdc8718fe57abc1bf91bc98b584ad441b4f19b0c68ed5349c65d8cfe0e0a017df209452723d3bcd1949fe14cbde5cd5e2088d6bedd4af3a6739ece@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>@ethstats.dencun-devnet-12.ethpandaops.io
            ethereumjs:
              - --gethGenesis=/data/network-config/genesis.json
              - --bootnodes=enode://59744008cb2de257daf3bdaa4fa34428c447e82705893be42a7407f20a84e45231b942c56e6bd771cbfb79c13b08eb85a002fe78cfd0c19b8634505aabed01db@64.226.104.183:30303?discport=30303,enode://ba216cbfc0fdc8718fe57abc1bf91bc98b584ad441b4f19b0c68ed5349c65d8cfe0e0a017df209452723d3bcd1949fe14cbde5cd5e2088d6bedd4af3a6739ece@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --sync=full
              - --maxPeers=25
              - --isSingleNode=true
              - --logLevel=debug
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QC062-OmCxOQlgGZ5RrMZTbXnusl94Zowgt3_dIDqQhdE-LzN4u4csp-pEmWAXVHfiFhap8aAdRYifTLUJAgvBGGAYwa1U8fgmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk,enr:-LK4QOFXZ1ZMEwJUIQP3OxxyfVs4jdxo7cpeWhLgIUyMt4dfNU5bZNrmod7-IP_HhgpCxW8QxGvzLBk3zlhvzNuEhhRrh2F0dG5ldHOIAAAAAAAAAAaEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQKVDZre1slkhn4d53LOHOEzxC3P5d8RLTRLUzf89KPWA4N0Y3CCIyiDdWRwgiMo,enr:-MS4QM2LKhnsinJ7rE9MIPMS1iWKK8_65b4S0h03GLkOL6dgYveLmW9ySPMVYt-jL0Y5NrQJ6kZDgiUiKIJX6x6GzXAEh2F0dG5ldHOIAIABAAAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQI2OOcP409cbfYB6yOZOi0rUIav9nlafclHO8SCyYzxRohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-Ma4QMPWmkaKF6kGBg0zY2dx2QVpwWwnf_qN7SE-fQBvZfZhbsb8QMs2mPb0CSKHMsFggX-u08L0G5JK1l8TbzTInwSCAUiHYXR0bmV0c4gAAABgAAAAAIRldGgykOycddRQQwOZ__________-CaWSCdjSCaXCEhtGRw4RxdWljgiMpiXNlY3AyNTZrMaED6-V-zX89UURu-AvfAc2H_sr1eF4ZnU_ArsYrtW9g_qGIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QC062-OmCxOQlgGZ5RrMZTbXnusl94Zowgt3_dIDqQhdE-LzN4u4csp-pEmWAXVHfiFhap8aAdRYifTLUJAgvBGGAYwa1U8fgmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk,enr:-LK4QOFXZ1ZMEwJUIQP3OxxyfVs4jdxo7cpeWhLgIUyMt4dfNU5bZNrmod7-IP_HhgpCxW8QxGvzLBk3zlhvzNuEhhRrh2F0dG5ldHOIAAAAAAAAAAaEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQKVDZre1slkhn4d53LOHOEzxC3P5d8RLTRLUzf89KPWA4N0Y3CCIyiDdWRwgiMo,enr:-MS4QM2LKhnsinJ7rE9MIPMS1iWKK8_65b4S0h03GLkOL6dgYveLmW9ySPMVYt-jL0Y5NrQJ6kZDgiUiKIJX6x6GzXAEh2F0dG5ldHOIAIABAAAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQI2OOcP409cbfYB6yOZOi0rUIav9nlafclHO8SCyYzxRohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-Ma4QMPWmkaKF6kGBg0zY2dx2QVpwWwnf_qN7SE-fQBvZfZhbsb8QMs2mPb0CSKHMsFggX-u08L0G5JK1l8TbzTInwSCAUiHYXR0bmV0c4gAAABgAAAAAIRldGgykOycddRQQwOZ__________-CaWSCdjSCaXCEhtGRw4RxdWljgiMpiXNlY3AyNTZrMaED6-V-zX89UURu-AvfAc2H_sr1eF4ZnU_ArsYrtW9g_qGIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=ARCHIVE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --Xpeer-rate-limit=100000
              - --Xpeer-request-limit=1000
              - --ignore-weak-subjectivity-period-enabled
              - --Xepochs-store-blobs=max # Keep the blobs forever
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --pprofaddr=0.0.0.0
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QC062-OmCxOQlgGZ5RrMZTbXnusl94Zowgt3_dIDqQhdE-LzN4u4csp-pEmWAXVHfiFhap8aAdRYifTLUJAgvBGGAYwa1U8fgmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QOFXZ1ZMEwJUIQP3OxxyfVs4jdxo7cpeWhLgIUyMt4dfNU5bZNrmod7-IP_HhgpCxW8QxGvzLBk3zlhvzNuEhhRrh2F0dG5ldHOIAAAAAAAAAAaEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQKVDZre1slkhn4d53LOHOEzxC3P5d8RLTRLUzf89KPWA4N0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-MS4QM2LKhnsinJ7rE9MIPMS1iWKK8_65b4S0h03GLkOL6dgYveLmW9ySPMVYt-jL0Y5NrQJ6kZDgiUiKIJX6x6GzXAEh2F0dG5ldHOIAIABAAAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQI2OOcP409cbfYB6yOZOi0rUIav9nlafclHO8SCyYzxRohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-Ma4QMPWmkaKF6kGBg0zY2dx2QVpwWwnf_qN7SE-fQBvZfZhbsb8QMs2mPb0CSKHMsFggX-u08L0G5JK1l8TbzTInwSCAUiHYXR0bmV0c4gAAABgAAAAAIRldGgykOycddRQQwOZ__________-CaWSCdjSCaXCEhtGRw4RxdWljgiMpiXNlY3AyNTZrMaED6-V-zX89UURu-AvfAc2H_sr1eF4ZnU_ArsYrtW9g_qGIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QC062-OmCxOQlgGZ5RrMZTbXnusl94Zowgt3_dIDqQhdE-LzN4u4csp-pEmWAXVHfiFhap8aAdRYifTLUJAgvBGGAYwa1U8fgmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk,enr:-LK4QOFXZ1ZMEwJUIQP3OxxyfVs4jdxo7cpeWhLgIUyMt4dfNU5bZNrmod7-IP_HhgpCxW8QxGvzLBk3zlhvzNuEhhRrh2F0dG5ldHOIAAAAAAAAAAaEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQKVDZre1slkhn4d53LOHOEzxC3P5d8RLTRLUzf89KPWA4N0Y3CCIyiDdWRwgiMo,enr:-MS4QM2LKhnsinJ7rE9MIPMS1iWKK8_65b4S0h03GLkOL6dgYveLmW9ySPMVYt-jL0Y5NrQJ6kZDgiUiKIJX6x6GzXAEh2F0dG5ldHOIAIABAAAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQI2OOcP409cbfYB6yOZOi0rUIav9nlafclHO8SCyYzxRohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-Ma4QMPWmkaKF6kGBg0zY2dx2QVpwWwnf_qN7SE-fQBvZfZhbsb8QMs2mPb0CSKHMsFggX-u08L0G5JK1l8TbzTInwSCAUiHYXR0bmV0c4gAAABgAAAAAIRldGgykOycddRQQwOZ__________-CaWSCdjSCaXCEhtGRw4RxdWljgiMpiXNlY3AyNTZrMaED6-V-zX89UURu-AvfAc2H_sr1eF4ZnU_ArsYrtW9g_qGIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
              - --self-limiter=blob_sidecars_by_range:256/10
              - --debug-level=debug
              - --quic-port=9001
              - --enr-quic-port=9001
              - --slasher
              - --slasher-history-length=256
              - --slasher-max-db-size=16
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --bootstrap-node=enr:-Iq4QC062-OmCxOQlgGZ5RrMZTbXnusl94Zowgt3_dIDqQhdE-LzN4u4csp-pEmWAXVHfiFhap8aAdRYifTLUJAgvBGGAYwa1U8fgmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QOFXZ1ZMEwJUIQP3OxxyfVs4jdxo7cpeWhLgIUyMt4dfNU5bZNrmod7-IP_HhgpCxW8QxGvzLBk3zlhvzNuEhhRrh2F0dG5ldHOIAAAAAAAAAAaEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhEDiaLeJc2VjcDI1NmsxoQKVDZre1slkhn4d53LOHOEzxC3P5d8RLTRLUzf89KPWA4N0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-MS4QM2LKhnsinJ7rE9MIPMS1iWKK8_65b4S0h03GLkOL6dgYveLmW9ySPMVYt-jL0Y5NrQJ6kZDgiUiKIJX6x6GzXAEh2F0dG5ldHOIAIABAAAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQI2OOcP409cbfYB6yOZOi0rUIav9nlafclHO8SCyYzxRohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-Ma4QMPWmkaKF6kGBg0zY2dx2QVpwWwnf_qN7SE-fQBvZfZhbsb8QMs2mPb0CSKHMsFggX-u08L0G5JK1l8TbzTInwSCAUiHYXR0bmV0c4gAAABgAAAAAIRldGgykOycddRQQwOZ__________-CaWSCdjSCaXCEhtGRw4RxdWljgiMpiXNlY3AyNTZrMaED6-V-zX89UURu-AvfAc2H_sr1eF4ZnU_ArsYrtW9g_qGIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: ethereum/client-go
      tag: v1.13.10
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: dencun-devnet-12
      testnet: dencun-devnet-12
      ethereum_network: dencun-devnet-12
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 5000m
        memory: 8Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.dencun-devnet-12.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.dencun-devnet-12.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.dencun-devnet-12.ethpandaops.io/el/besu.json;
            BOOTNODES_URI=https://config.dencun-devnet-12.ethpandaops.io/el/bootnodes.txt;
            TRUSTED_SETUP_URI=https://config.dencun-devnet-12.ethpandaops.io/trusted_setup.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/bootnodes.txt $BOOTNODES_URI;
              wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethereum/client-go:v1.13.10
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --state.scheme=path --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: consensys/teku
      tag: 24.1.0
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: dencun-devnet-12
      testnet: dencun-devnet-12
      ethereum_network: dencun-devnet-12
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 5000m
        memory: 8Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.dencun-devnet-12.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.dencun-devnet-12.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootnodes.txt;
          TRUSTED_SETUP_URI=https://config.dencun-devnet-12.ethpandaops.io/trusted_setup.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootnodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootnodes2.txt;
          mv /data/network-config/bootnodes2.txt /data/network-config/bootnodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
