
goomy_container_networks: "{{ docker_networks_shared }}"
goomy_rpc_urls:
  - "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.lighthouse-geth-1.{{ network_subdomain }}"

goomy_scenario: "combined"
goomy_extra_args: ["--sidecars", "6", "--throughput", "6", "--max-pending", "50"]
